# Generated by Django 6.0.4 on 2026-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_education_experience_sitesettings_skill_sociallink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=200)),
                ('title', models.CharField(default='Full Stack Developer', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline under your title', max_length=500)),
                ('profile_image', models.ImageField(blank=True, help_text='Your photo', upload_to='profile/')),
                ('email', models.EmailField(default='your.email@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_subtitle', models.CharField(blank=True, max_length=500)),
                ('about_content', models.TextField(blank=True, help_text='Main about section content')),
                ('about_image', models.ImageField(blank=True, upload_to='profile/')),
                ('resume_cv', models.FileField(blank=True, help_text='Upload your CV/Resume PDF', upload_to='profile/')),
                ('hero_stats', models.JSONField(blank=True, default=dict, help_text='{"projects": "50+", "years": "3+", "clients": "30+"}')),
                ('response_time', models.CharField(blank=True, default='Within 24 hours', max_length=100)),
                ('footer_text', models.TextField(blank=True, help_text='Custom footer text')),
                ('footer_copyright', models.CharField(blank=True, max_length=200)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID', max_length=50)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-code', help_text='Font Awesome icon class', max_length=100)),
                ('icon_color', models.CharField(default='sky', help_text='Tailwind color class (sky, emerald, purple, orange, teal, pink)', max_length=50)),
                ('features', models.JSONField(blank=True, default=list, help_text='["Feature 1", "Feature 2"]')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('stackoverflow', 'Stack Overflow'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('medium', 'Medium'), ('dev', 'Dev.to'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=50, unique=True),
        ),
    ]
